In [34]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Part 1: Showing the Dataset

In [36]:
df = pd.read_csv('zomato_res.csv')
df

Additional_outlet_count  Call Cost_for_two  \
0      1 more outlet in Mumbai  True       ₹1,500   
1      1 more outlet in Mumbai  True         ₹800   
2                          NaN  True       ₹2,500   
3                          NaN  True       ₹1,800   
4     2 more outlets in Mumbai  True         ₹450   
...                        ...   ...          ...   
7280                       NaN  True         ₹600   
7281                       NaN  True         ₹550   
7282                       NaN  True         ₹350   
7283                       NaN  True       ₹2,000   
7284                       NaN  True         ₹600   

                                               Cuisines  \
0           Finger Food, Continental, European, Italian   
1                                                 Pizza   
2                                               Seafood   
3                              Finger Food, Continental   
4         North Indian, Street Food, Fast Food, Chinese   
...                                                 ...   
7280  South Indian, North Indian, Chinese, Fast Food...   
7281                            Fast Food, North Indian   
7282                        Fast Food, Beverages, Rolls   
7283                                   Seafood, Chinese   
7284                     North Indian, Chinese, Seafood   

                                Delivery_Time_min_order  \
0                                                   NaN   
1                                                   NaN   
2                                                   NaN   
3                                                   NaN   
4     45 min                                        ...   
...                                                 ...   
7280  45 min                                        ...   
7281  20 min                                        ...   
7282                                                NaN   
7283  40 min                                        ...   
7284                                                NaN   

                                               Features  Home_Delivery  \
0     Food Hygiene Rated Restaurants In Mumbai, Best...          False   
1                       Value For Money, Best of Mumbai          False   
2                         Super Seafood, Best of Mumbai          False   
3     Where's The Party?, Best of Mumbai, Food Hygie...          False   
4                                                   NaN           True   
...                                                 ...            ...   
7280                                                NaN           True   
7281                                                NaN           True   
7282                                                NaN          False   
7283                                                NaN           True   
7284                                                NaN          False   

                                      Operational_hours  \
0                                12noon – 1am (Mon-Sun)   
1                              11am – 12:30AM (Mon-Sun)   
2        Closed (Mon),12noon – 3pm, 7pm – 12midnight...   
3                                12noon – 1am (Mon-Sun)   
4                 12noon – 4pm, 7pm – 11:45pm (Mon-Sun)   
...                                                 ...   
7280                         8am – 12midnight (Mon-Sun)   
7281  9am – 9pm (Mon, Wed, Thu, Fri, Sat, Sun), Clos...   
7282                             8am – 1:30am (Mon-Sun)   
7283                         12noon – 12:30AM (Mon-Sun)   
7284                        11am – 12midnight (Mon-Sun)   

                                           Rating_votes  \
0     4.9                                        132...   
1     4.6                                        597...   
2     4.5                                        143...   
3     4.9                                        327...   
4     4.1                                        142...   


# Part 2: Data Cleaning

In [37]:
# Checking the Null Value
df.isnull().sum()

Additional_outlet_count    6285
Call                          0
Cost_for_two                  0
Cuisines                      1
Delivery_Time_min_order    4771
Features                   5695
Home_Delivery                 0
Operational_hours            12
Rating_votes                  0
Restaurant_Location          19
Restaurant_Name               0
Restaurant_Type             656
View_Menu                     0
dtype: int64

In [38]:
# Removing the Null Value of Cuisines and Features --> Because these two will be our main indicator
df = df.dropna(subset=['Cuisines', 'Features', 'Restaurant_Type'])
df.isnull().sum()

Additional_outlet_count    1076
Call                          0
Cost_for_two                  0
Cuisines                      0
Delivery_Time_min_order     549
Features                      0
Home_Delivery                 0
Operational_hours             0
Rating_votes                  0
Restaurant_Location           0
Restaurant_Name               0
Restaurant_Type               0
View_Menu                     0
dtype: int64

# Part 3: Combining the Indicators

In [30]:
# print(f'rows = {df.shape[0]} | columns = {df.shape[1]}')
# Combining all of the column that are selected as indicators
# df['multi'] = (pd.Series(df[['Cuisines', 'Features', 'Restaurant_Type']].values.tolist()).str.join(','))
# df

Additional_outlet_count  Call Cost_for_two  \
0      1 more outlet in Mumbai  True       ₹1,500   
1      1 more outlet in Mumbai  True         ₹800   
2                          NaN  True       ₹2,500   
3                          NaN  True       ₹1,800   
5                          NaN  True       ₹1,600   
...                        ...   ...          ...   
7018  5 more outlets in Mumbai  True         ₹600   
7034                       NaN  True         ₹300   
7042                       NaN  True         ₹500   
7049                       NaN  True         ₹400   
7063                       NaN  True         ₹700   

                                         Cuisines  \
0     Finger Food, Continental, European, Italian   
1                                           Pizza   
2                                         Seafood   
3                        Finger Food, Continental   
5           Modern Indian, European, Pizza, Grill   
...                                           ...   
7018                      South Indian, Beverages   
7034        Mughlai, Biryani, North Indian, Kebab   
7042                   Mughlai, Lucknowi, Biryani   
7049                          North Indian, Rolls   
7063              North Indian, Chinese, American   

                                Delivery_Time_min_order  \
0                                                   NaN   
1                                                   NaN   
2                                                   NaN   
3                                                   NaN   
5                                                   NaN   
...                                                 ...   
7018  50 min                                        ...   
7034  45 min                                        ...   
7042                                                NaN   
7049  45 min                                        ...   
7063                                                NaN   

                                               Features  Home_Delivery  \
0     Food Hygiene Rated Restaurants In Mumbai, Best...          False   
1                       Value For Money, Best of Mumbai          False   
2                         Super Seafood, Best of Mumbai          False   
3     Where's The Party?, Best of Mumbai, Food Hygie...          False   
5     Best of Mumbai, Food Hygiene Rated Restaurants...          False   
...                                                 ...            ...   
7018                              15% off on all orders           True   
7034                              10% off on all orders           True   
7042                        10% off on your first order          False   
7049                              20% off on all orders           True   
7063                                           Rooftops          False   

                                   Operational_hours  \
0                             12noon – 1am (Mon-Sun)   
1                           11am – 12:30AM (Mon-Sun)   
2     Closed (Mon),12noon – 3pm, 7pm – 12midnight...   
3                             12noon – 1am (Mon-Sun)   
5                                1pm – 1am (Mon-Sun)   
...                                              ...   
7018                      8am – 12midnight (Mon-Sun)   
7034                           11am – 11pm (Mon-Sun)   
7042                             7pm – 4am (Mon-Sun)   
7049  11:30am – 4pm, 6pm – 11:30pm (Mon, Wed, Thu...   
7063                          3pm – 1:30am (Mon-Sun)   

                                           Rating_votes  \
0     4.9                                        132...   
1     4.6                                        597...   
2     4.5                                        143...   
3     4.9                                        327...   
5     4.8                                        198...   
...                                                 ...   
7018  3.7                                        

In [6]:
# We have a problem showing that only the first 613 rows have their indicators merged.
# So I decided to split it into 3 parts with the multiplier of 613

#### Saving as "Contoh" ####
# df.to_excel('contoh.xlsx', sheet_name='sheet1')

#### Re-open Contoh, then make a copy on it to include the 614th-1226th row to a new dataset
# main = pd.read_excel('contoh.xlsx', sheet_name="sheet1")
# main.drop(0:612, axis=0)

In [39]:
A = pd.read_excel('A.xlsx', sheet_name='PartA')
B = pd.read_excel('A.xlsx', sheet_name='PartB')
C = pd.read_excel('A.xlsx', sheet_name='PartC')

In [40]:
B['multi'] = (pd.Series(df[['Cuisines', 'Features', 'Restaurant_Type']].values.tolist()).str.join(','))
C['multi'] = (pd.Series(df[['Cuisines', 'Features', 'Restaurant_Type']].values.tolist()).str.join(','))

In [41]:
D = pd.concat([A, B, C])

In [22]:
# Checking on how much distinct multi (combined between cuisines, restaurant types, and features)
ext = CountVectorizer(tokenizer= lambda x: x.split(','))
zmulti = ext.fit_transform(D['multi'].head(1316))
len(ext.get_feature_names())

339

In [11]:
# Inserting the vector into an array and check the shape
print(zmulti.toarray())
print(zmulti.toarray().shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(1316, 339)


In [12]:
# Reset index in order for the restaurant that have the original index between 1317 and onwards
#to be included in the Cosine Similarity

#Formula:
D = D.reset_index()
del D['index']

# Part 4: Cosine Similarity

Cosine Similarity Formula = $ \displaystyle \frac {\sum (_{n}A x _{n}B)} {\sqrt {\sum (_{n}A)^2} x \sqrt {\sum (_{n}B)^2}} $

In [13]:
# Measure the similarity between Cuisines using Cosine similarity
cos_score = cosine_similarity(zmulti)
cos_score[0]

array([1.        , 0.1767767 , 0.31622777, ..., 0.375     , 0.        ,
       0.11785113])

# Part 5: Recommendation

In [14]:
# Checking the Index of the favorite restaurant input by the user, assuming it is 'Waters 24 - Vintage Cafe' in this case
resto_input = "Joey's Pizza"
resto_index = D[D['Restaurant_Name'] == resto_input].index[0]
resto_index

1

In [15]:
# Check if the index of favorite restaurant has 100% similarity or not
a = list(enumerate(cos_score[resto_index]))
a[resto_index]

(1, 1.0)

In [16]:
# Ranking List
resto_sug = sorted(a, key=lambda x:x[1], reverse=True)
resto_sug.remove(a[resto_index])
resto_sug[:10]

[(613, 1.0),
 (1225, 1.0),
 (183, 0.6123724356957946),
 (901, 0.6123724356957946),
 (83, 0.5773502691896258),
 (279, 0.5773502691896258),
 (405, 0.5773502691896258),
 (464, 0.5773502691896258),
 (546, 0.5773502691896258),
 (741, 0.5773502691896258)]

In [17]:
# Restaurant Recommendation for the user (in this case'Waters 24 - Vintage Cafe')
for i in resto_sug[:10]:
    print(D.iloc[i[0]]['Restaurant_Name'])

Konkan Chilly
Hyderabad Xpress
Quench - All Day Pub
99 Bollywood Bar
Olive Bar & Kitchen
266 - The Wine Room And Bar
Hariprasad
Smaaash
Above & Beyond
Gutt Gully


In [23]:
ext.get_feature_names()

[' afghani',
 ' all-day dining',
 ' american',
 ' andhra',
 ' arabian',
 ' arabian nights',
 ' asian',
 ' awadhi',
 ' bakery',
 ' bar food',
 ' bbq',
 ' beer in a bar',
 ' bengali',
 ' best food',
 ' best of mumbai',
 ' beverages',
 ' biryani',
 ' brilliant biryanis',
 ' british',
 ' bubble tea',
 ' burger',
 ' burmese',
 ' cafe',
 ' cafe food',
 ' cantonese',
 ' charcoal chicken',
 ' chettinad',
 ' chinese',
 ' coffee',
 ' continental',
 ' corporate favorites',
 ' custom bakes',
 ' dessert picks',
 ' desserts',
 ' dumplings',
 ' european',
 ' european & mediterranean',
 ' fast food',
 ' finger food',
 ' food hygiene rated restaurants in mumbai',
 ' french',
 ' fusion',
 ' german',
 ' gigs and events',
 ' goan',
 ' gourmet pizza',
 ' great buffets',
 ' greek',
 ' grill',
 ' gujarati',
 ' happy hours',
 ' healthy food',
 ' hot pot',
 ' hot stuff by bira 91',
 ' hyderabadi',
 ' ice cream',
 ' indian',
 ' indonesian',
 ' international',
 ' international coffee day',
 ' irani cafés',
 ' ir